server:
  port: 8086

spring:
  application:
    name: post
  datasource:
    username: 'vlogiversecode'
    url: jdbc:postgresql://localhost:5433/post
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka